using System.Buffers.Binary;
using System.Collections.Concurrent;
using System.Security.Cryptography;
using System.Text;
using System.Reflection;
using MusicMachine.App;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.LogicalTree;
using MusicMachine.Audio;
using MusicMachine.Core;

namespace MusicMachine.Tests;

public sealed class StreamingExportTests
{
    public static IEnumerable<object[]> QoaBoundaries()
    {
        foreach (int frames in new[] { 1, 19, 20, 21, 5119, 5120, 5121, 10241 })
            foreach (int channels in new[] { 1, 2, 8 }) yield return [frames, channels];
    }

    [Theory, MemberData(nameof(QoaBoundaries))]
    public void StreamedQoaMatchesInMemoryAcrossSliceFrameAndChannelBoundaries(int frames, int channels)
    {
        short[] pcm = Noise(frames, channels);
        byte[] expected = QoaCodec.Encode(pcm, 44100, channels);
        Assert.Equal(expected, StreamQoa(pcm, 44100, channels));
    }

    [Fact] public void StreamedQoaMatchesFrozenPreStreamingEncoderAndOfficialReference()
    {
        // Captured from the pre-streaming encoder, not generated by the encoder under test.
        // This covers full-range PCM, 1/2/8 channels, partial slices and predictor carry across frames.
        using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        foreach (object[] test in QoaBoundaries()) hash.AppendData(StreamQoa(Noise((int)test[0], (int)test[1]), 44100, (int)test[1]));
        Assert.Equal("F78205A0C2D10F89F20CE70A66A1EE302C20BD37316ECB329750D6696DE27BA7", Convert.ToHexString(hash.GetHashAndReset()));
        var input = new short[82];
        for (int i = 0; i < 41; i++) { input[i * 2] = (short)(i * 500 - 10000); input[i * 2 + 1] = (short)-input[i * 2]; }
        // Official phoboslab/qoa qoa_write fixture also used by AudioTests.
        const string reference = "cW9hZgAAACkCALuAACkAWAAAAAAAAAAAAAAAAOAAQAAAAAAAAAAAAAAAAADgAEAA34sEkENEggjNyCCCCASAQTXKAhgQSKIAT4EBokgEgggYAAAAAAAAAEIAAAAAAAAA";
        Assert.Equal(Convert.FromBase64String(reference), StreamQoa(input, 48000, 2));
    }

    [Theory]
    [InlineData(-1L, 48000, 2)] [InlineData(0L, 48000, 2)] [InlineData(4294967296L, 48000, 2)]
    [InlineData(1L, 0, 2)] [InlineData(1L, 16777216, 2)] [InlineData(1L, 48000, 0)] [InlineData(1L, 48000, 9)]
    public void QoaInvalidMetadataDoesNotWriteAnything(long frames, int rate, int channels)
    {
        using var stream = new MemoryStream(); stream.WriteByte(123);
        Assert.Throws<ArgumentException>(() => new QoaCodec.Writer(stream, frames, rate, channels));
        Assert.Equal(new byte[] { 123 }, stream.ToArray());
    }

    [Fact] public void QoaWriterChecksStreamCancellationCompletenessAndFinalPartialFrame()
    {
        Assert.Throws<ArgumentNullException>(() => new QoaCodec.Writer(null!, 1));
        using var readOnly = new MemoryStream([1, 2], writable: false);
        Assert.Throws<ArgumentException>(() => new QoaCodec.Writer(readOnly, 1));
        using var cancelled = new CancellationTokenSource(); cancelled.Cancel();
        using var stream = new MemoryStream();
        Assert.ThrowsAny<OperationCanceledException>(() => new QoaCodec.Writer(stream, 5121, cancellationToken: cancelled.Token));
        Assert.Equal(0, stream.Length);
        var writer = new QoaCodec.Writer(stream, 5121);
        Assert.Throws<InvalidOperationException>(() => writer.Complete());
        Assert.Throws<ArgumentException>(() => writer.WriteFrame([]));
        Assert.Throws<ArgumentException>(() => writer.WriteFrame(new short[10238]));
        Assert.Throws<ArgumentException>(() => writer.WriteFrame(new short[10241]));
        Assert.Throws<ArgumentException>(() => writer.WriteFrame(new short[10242]));
        Assert.ThrowsAny<OperationCanceledException>(() => writer.WriteFrame(new short[10240], cancelled.Token));
        Assert.Equal(8, stream.Length);
        writer.WriteFrame(new short[10240]);
        long firstLength = stream.Length;
        Assert.Throws<InvalidOperationException>(() => writer.Complete());
        Assert.Throws<ArgumentException>(() => writer.WriteFrame(new short[10240]));
        Assert.Equal(firstLength, stream.Length);
        writer.WriteFrame(new short[2]); writer.Complete(); writer.Complete();
        Assert.Throws<ArgumentException>(() => writer.WriteFrame(new short[2]));
        Assert.ThrowsAny<OperationCanceledException>(() => writer.Complete(cancelled.Token));
        Assert.Equal(QoaCodec.Encode(new short[10242]), stream.ToArray());
        Assert.True(stream.CanWrite); // The caller retains stream ownership.
        using var maximum = new MemoryStream();
        _ = new QoaCodec.Writer(maximum, uint.MaxValue, 0xffffff, 8);
        Assert.Equal(uint.MaxValue, BinaryPrimitives.ReadUInt32BigEndian(maximum.ToArray().AsSpan(4)));
    }

    [Theory] [InlineData(false)] [InlineData(true)]
    public async Task SongAndSpanExportsMatchOldRenderBasedBytesIncludingNaturalTails(bool qoa)
    {
        string directory = NewDirectory();
        try
        {
            Song song = Tone();
            foreach (bool tail in new[] { false, true })
            {
                float[] pcm = OfflineExporter.Render(song, includeTail: tail);
                byte[] expected = qoa ? QoaCodec.Encode(pcm.Select(OfflineExporter.ToPcm16).ToArray()) : OldWav(pcm);
                string path = Path.Combine(directory, "audio");
                Write(path, song, qoa, includeTail: tail); Assert.Equal(expected, File.ReadAllBytes(path));
                await WriteAsync(path, song, qoa, includeTail: tail); Assert.Equal(expected, File.ReadAllBytes(path));
                if (qoa) OfflineExporter.WriteQoa(path, pcm); else OfflineExporter.WriteWav(path, pcm);
                Assert.Equal(expected, File.ReadAllBytes(path));
                Assert.Single(Directory.GetFiles(directory));
            }
        }
        finally { Directory.Delete(directory, true); }
    }

    [Theory] [InlineData(false)] [InlineData(true)]
    public void SpanExportsPreservePcmQuantizationAndAlternateRates(bool qoa)
    {
        float[] pcm = [float.NaN, float.PositiveInfinity, float.NegativeInfinity, -2, 2, 0, -1, 1, -.5f, .5f, -1f / 65534, 1f / 65534];
        string directory = NewDirectory();
        try
        {
            string path = Path.Combine(directory, "audio");
            if (qoa) OfflineExporter.WriteQoa(path, pcm, 44100); else OfflineExporter.WriteWav(path, pcm, 44100);
            Assert.Equal(qoa ? QoaCodec.Encode(pcm.Select(OfflineExporter.ToPcm16).ToArray(), 44100) : OldWav(pcm, 44100), File.ReadAllBytes(path));
            if (!qoa) { OfflineExporter.WriteWav(path, ReadOnlySpan<float>.Empty); Assert.Equal(OldWav([]), File.ReadAllBytes(path)); }
        }
        finally { Directory.Delete(directory, true); }
    }

    [Theory] [InlineData(false)] [InlineData(true)]
    public async Task PreCancelledSyncAndAsyncExportsPreserveExistingDestination(bool qoa)
    {
        string directory = NewDirectory();
        try
        {
            string path = Path.Combine(directory, "audio"); File.WriteAllText(path, "keep");
            using var cancellation = new CancellationTokenSource(); cancellation.Cancel();
            Assert.ThrowsAny<OperationCanceledException>(() => Write(path, Tone(), qoa, cancellation.Token));
            await Assert.ThrowsAnyAsync<OperationCanceledException>(() => WriteAsync(path, Tone(), qoa, cancellation.Token));
            Assert.Equal("keep", File.ReadAllText(path)); Assert.Single(Directory.GetFiles(directory));
        }
        finally { Directory.Delete(directory, true); }
    }

    [Theory] [InlineData(false)] [InlineData(true)]
    public void CooperativeExportsYieldAndCancelAfterWritingOnASingleThread(bool qoa)
    {
        string directory = NewDirectory();
        SynchronizationContext? previous = SynchronizationContext.Current;
        using var context = new PumpContext();
        try
        {
            SynchronizationContext.SetSynchronizationContext(context);
            string path = Path.Combine(directory, "audio"); File.WriteAllText(path, "keep");
            using var cancellation = new CancellationTokenSource();
            Task export = WriteAsync(path, Tone(), qoa, cancellation.Token);
            Assert.False(export.IsCompleted);
            string temporary = Assert.Single(Directory.GetFiles(directory, "*.tmp"));
            context.RunOne(); // Let at least one actual render/encode/write block finish, then regain control.
            Assert.False(export.IsCompleted);
            Assert.True(new FileInfo(temporary).Length > (qoa ? 8 : 44));
            Assert.Equal("keep", File.ReadAllText(path));
            cancellation.Cancel();
            while (!export.IsCompleted) context.RunOne();
            Assert.ThrowsAny<OperationCanceledException>(() => export.GetAwaiter().GetResult());
            Assert.Equal("keep", File.ReadAllText(path)); Assert.Single(Directory.GetFiles(directory));
        }
        finally { SynchronizationContext.SetSynchronizationContext(previous); Directory.Delete(directory, true); }
    }

    [Theory] [InlineData(false)] [InlineData(true)]
    public async Task InvalidOutputLengthsAreRejectedBeforeOpeningAnyOutput(bool qoa)
    {
        // No voices/events, but enough low-tempo rows to overflow the container's 32-bit length.
        var pattern = new Pattern { Id = "long", Length = 4096 };
        var song = new Song { Bpm = 20, RowsPerBeat = 1, Tracks = [], Instruments = [], Patterns = [pattern],
            Arrangement = [new() { PatternId = pattern.Id, Repeats = qoa ? 8 : 2 }] };
        string directory = NewDirectory();
        try
        {
            string path = Path.Combine(directory, "audio"); File.WriteAllText(path, "keep");
            Assert.Throws<ArgumentException>(() => Write(path, song, qoa));
            await Assert.ThrowsAsync<ArgumentException>(() => WriteAsync(path, song, qoa));
            // The invalid format must win over even a nonexistent destination directory.
            Assert.Throws<ArgumentException>(() => Write(Path.Combine(directory, "absent", "audio"), song, qoa));
            Assert.Equal("keep", File.ReadAllText(path)); Assert.Single(Directory.GetFiles(directory));
        }
        finally { Directory.Delete(directory, true); }
    }

    [Theory] [InlineData(false)] [InlineData(true)]
    public void InvalidSpanMetadataPreservesExistingDestination(bool qoa)
    {
        string directory = NewDirectory();
        try
        {
            string path = Path.Combine(directory, "audio"); File.WriteAllText(path, "keep");
            if (qoa)
            {
                Assert.Throws<ArgumentException>(() => OfflineExporter.WriteQoa(path, new float[3]));
                Assert.Throws<ArgumentException>(() => OfflineExporter.WriteQoa(path, Array.Empty<float>()));
                Assert.Throws<ArgumentException>(() => OfflineExporter.WriteQoa(path, new float[2], 0));
                Assert.Throws<ArgumentException>(() => OfflineExporter.WriteQoa(path, new float[2], 0x1000000));
            }
            else
            {
                Assert.Throws<ArgumentException>(() => OfflineExporter.WriteWav(path, new float[3]));
                Assert.Throws<ArgumentException>(() => OfflineExporter.WriteWav(path, new float[2], 0));
                Assert.Throws<ArgumentException>(() => OfflineExporter.WriteWav(path, new float[2], int.MaxValue));
            }
            Assert.Equal("keep", File.ReadAllText(path)); Assert.Single(Directory.GetFiles(directory));
        }
        finally { Directory.Delete(directory, true); }
    }

    [Theory] [InlineData(false)] [InlineData(true)]
    public async Task FailedFinalReplacementCleansUpTemporaryFiles(bool qoa)
    {
        string directory = NewDirectory();
        try
        {
            string path = Path.Combine(directory, "occupied"); Directory.CreateDirectory(path);
            File.WriteAllText(Path.Combine(path, "keep"), "keep");
            Assert.ThrowsAny<IOException>(() => Write(path, Tone(), qoa));
            await Assert.ThrowsAnyAsync<IOException>(() => WriteAsync(path, Tone(), qoa));
            Assert.Equal("keep", File.ReadAllText(Path.Combine(path, "keep")));
            Assert.Empty(Directory.GetFiles(directory)); Assert.Single(Directory.GetDirectories(directory));
        }
        finally { Directory.Delete(directory, true); }
    }

    [Fact] public async Task StorageCommitCancellationBeforeOpenPreservesTheProviderDestination()
    {
        string directory = NewDirectory();
        try
        {
            string source = Path.Combine(directory, "audio"); File.WriteAllBytes(source, [1, 2, 3]);
            using var token = new CancellationTokenSource(); token.Cancel();
            using var file = new FakeStorageFile(); bool finalizing = false;
            await Assert.ThrowsAnyAsync<OperationCanceledException>(() => Commit(source, file, token.Token, () => finalizing = true));
            Assert.False(finalizing); Assert.Equal(0, file.Opens); Assert.Equal("keep"u8.ToArray(), file.Output.ToArray());
            await Assert.ThrowsAsync<FileNotFoundException>(() => Commit(source + ".missing", file, default, () => finalizing = true));
            Assert.False(finalizing); Assert.Equal(0, file.Opens); Assert.Equal("keep"u8.ToArray(), file.Output.ToArray());
        }
        finally { Directory.Delete(directory, true); }
    }

    [Theory] [InlineData("open")] [InlineData("write")] [InlineData("flush")]
    public async Task StorageCommitIgnoresLateUserCancellationAndFinishesAllBytes(string cancelAt)
    {
        string directory = NewDirectory();
        try
        {
            byte[] expected = Enumerable.Range(0, 200000).Select(i => (byte)i).ToArray();
            string source = Path.Combine(directory, "audio"); File.WriteAllBytes(source, expected);
            using var cancellation = new CancellationTokenSource();
            using var file = new FakeStorageFile(); bool finalizing = false;
            file.BeforeOpen = () => { Assert.True(finalizing); if (cancelAt == "open") cancellation.Cancel(); };
            file.Output.BeforeWrite = token =>
            {
                Assert.True(finalizing); Assert.False(token.CanBeCanceled);
                if (cancelAt == "write") cancellation.Cancel();
            };
            file.Output.BeforeFlush = token => { Assert.False(token.CanBeCanceled); if (cancelAt == "flush") cancellation.Cancel(); };
            await Commit(source, file, cancellation.Token, () => finalizing = true);
            Assert.True(cancellation.IsCancellationRequested); Assert.True(finalizing); Assert.Equal(1, file.Opens);
            Assert.True(file.Output.Closed); Assert.Equal(expected, file.Output.ToArray());
        }
        finally { Directory.Delete(directory, true); }
    }

    [Theory] [InlineData("open")] [InlineData("write")] [InlineData("close")]
    public async Task StorageProviderFailuresRemainErrorsAndDoNotPromiseRollback(string failureAt)
    {
        string directory = NewDirectory();
        try
        {
            string source = Path.Combine(directory, "audio"); byte[] expected = new byte[200000]; File.WriteAllBytes(source, expected);
            using var file = new FakeStorageFile(); bool finalizing = false;
            file.BeforeOpen = () => { if (failureAt == "open") throw new IOException("provider open failed"); };
            file.Output.FailWrite = failureAt == "write"; file.Output.FailClose = failureAt == "close";
            IOException error = await Assert.ThrowsAsync<IOException>(() => Commit(source, file, default, () => finalizing = true));
            Assert.Contains("provider", error.Message); Assert.True(finalizing); Assert.Equal(1, file.Opens);
            Assert.True(File.Exists(source));
            if (failureAt == "open") Assert.Equal("keep"u8.ToArray(), file.Output.ToArray());
            else Assert.True(file.Output.Closed);
            if (failureAt == "write") Assert.InRange(file.Output.ToArray().Length, 1, expected.Length - 1);
        }
        finally { Directory.Delete(directory, true); }
    }

    [Theory] [InlineData(false)] [InlineData(true)]
    public void SongOutputAllocationDoesNotGrowWithAudioDuration(bool qoa)
    {
        // Identical arrangement structure; only tempo changes duration by 20x.
        var pattern = new Pattern { Id = "a", Length = 4 };
        var song = new Song { Bpm = 400, RowsPerBeat = 1, Instruments = [], Tracks = [], Patterns = [pattern], Arrangement = [new() { PatternId = pattern.Id }] };
        string directory = NewDirectory();
        try
        {
            string path = Path.Combine(directory, "audio"); Write(path, song, qoa);
            long before = GC.GetAllocatedBytesForCurrentThread(); Write(path, song, qoa);
            long shortAllocation = GC.GetAllocatedBytesForCurrentThread() - before;
            long shortLength = new FileInfo(path).Length;
            song.Bpm = 20;
            before = GC.GetAllocatedBytesForCurrentThread(); Write(path, song, qoa);
            long longAllocation = GC.GetAllocatedBytesForCurrentThread() - before;
            Assert.True(new FileInfo(path).Length > shortLength * 19);
            Assert.InRange(longAllocation, 0, shortAllocation + 4096);
            Assert.InRange(longAllocation, 0, 128 * 1024);
        }
        finally { Directory.Delete(directory, true); }
    }

    [Fact] public void QoaWriterAllocationIsIndependentOfFrameCount()
    {
        var pcm = new short[5120 * 2];
        void Encode(int frames)
        {
            var writer = new QoaCodec.Writer(Stream.Null, frames * 5120L);
            for (int i = 0; i < frames; i++) writer.WriteFrame(pcm);
            writer.Complete();
        }
        Encode(1);
        long before = GC.GetAllocatedBytesForCurrentThread(); Encode(1);
        long single = GC.GetAllocatedBytesForCurrentThread() - before;
        before = GC.GetAllocatedBytesForCurrentThread(); Encode(64);
        long many = GC.GetAllocatedBytesForCurrentThread() - before;
        Assert.Equal(single, many); Assert.InRange(many, 0, 8192);
    }

    // Called by the existing headless editor regression on its single UI dispatcher.
    internal static void RunControlChecks(MainView view)
    {
        const BindingFlags fields = BindingFlags.Instance | BindingFlags.NonPublic;
        var busy = typeof(MainView).GetField("exportBusy", fields)!;
        var restart = typeof(MainView).GetField("updateRestartApproved", fields)!;
        var status = (TextBlock)typeof(MainView).GetField("status", fields)!.GetValue(view)!;
        object oldBusy = busy.GetValue(view)!, oldRestart = restart.GetValue(view)!;
        string? oldStatus = status.Text; object? oldTip = ToolTip.GetTip(status);
        try
        {
            busy.SetValue(view, true); restart.SetValue(view, false);
            Task<bool> close = view.RequestCloseAsync(); Assert.True(close.IsCompleted); Assert.False(close.GetAwaiter().GetResult());
            Assert.Contains("Finish or cancel", status.Text);
            restart.SetValue(view, true);
            close = view.RequestCloseAsync(); Assert.True(close.IsCompleted); Assert.False(close.GetAwaiter().GetResult());
            var makeProgress = typeof(MainView).GetMethod("ExportProgress", fields)!;
            using var rendering = new CancellationTokenSource();
            object?[] renderArgs = ["WAV", rendering, null];
            var renderDialog = (ContentControl)makeProgress.Invoke(view, renderArgs)!;
            Assert.True(renderDialog.GetLogicalDescendants().OfType<Button>().Single().IsEnabled);
            renderDialog.GetType().GetMethod("Close")!.Invoke(renderDialog, [null]);
            Assert.True(rendering.IsCancellationRequested);
            using var finalizing = new CancellationTokenSource();
            object?[] finalArgs = ["QOA", finalizing, null];
            var finalDialog = (ContentControl)makeProgress.Invoke(view, finalArgs)!;
            ((Action)finalArgs[2]!)();
            var cancel = finalDialog.GetLogicalDescendants().OfType<Button>().Single();
            Assert.False(cancel.IsEnabled);
            Assert.Contains(finalDialog.GetLogicalDescendants().OfType<TextBlock>(), t => t.Text == "Finalizing QOA…");
            cancel.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));
            Assert.False(finalizing.IsCancellationRequested);
            finalDialog.GetType().GetMethod("Close")!.Invoke(finalDialog, [null]);
            Assert.False(finalizing.IsCancellationRequested);
            close = view.RequestCloseAsync(); Assert.True(close.IsCompleted); Assert.False(close.GetAwaiter().GetResult());
            busy.SetValue(view, false);
            close = view.RequestCloseAsync(); Assert.True(close.IsCompleted); Assert.True(close.GetAwaiter().GetResult());
        }
        finally { busy.SetValue(view, oldBusy); restart.SetValue(view, oldRestart); status.Text = oldStatus; ToolTip.SetTip(status, oldTip); }
    }

    private static void Write(string path, Song song, bool qoa, CancellationToken token = default, bool includeTail = false)
    { if (qoa) OfflineExporter.WriteQoa(path, song, token, includeTail); else OfflineExporter.WriteWav(path, song, token, includeTail); }
    private static Task WriteAsync(string path, Song song, bool qoa, CancellationToken token = default, bool includeTail = false)
        => qoa ? OfflineExporter.WriteQoaAsync(path, song, token, includeTail) : OfflineExporter.WriteWavAsync(path, song, token, includeTail);
    private static string NewDirectory() => Directory.CreateDirectory(Path.Combine(Path.GetTempPath(), "musicmachine-stream-" + Guid.NewGuid().ToString("N"))).FullName;
    private static Song Tone()
    {
        var song = DemoSong.CreateEmpty(); song.Bpm = 137; song.Patterns[0].Length = 3;
        var part = song.Patterns[0].GetTrack(song.Tracks[0].Id); part.Rows[0] = new() { Kind = NoteKind.Note, Pitch = 69, Effects = ["A37", "V80"] };
        song.Instruments[0].Waveform = Waveform.Noise;
        return song;
    }
    private static short[] Noise(int frames, int channels)
    {
        var pcm = new short[frames * channels]; uint state = 123456;
        for (int i = 0; i < pcm.Length; i++) { state = unchecked(state * 1664525 + 1013904223); pcm[i] = unchecked((short)(state >> 16)); }
        return pcm;
    }
    private static byte[] StreamQoa(short[] pcm, int sampleRate, int channels)
    {
        using var stream = new MemoryStream();
        var writer = new QoaCodec.Writer(stream, pcm.Length / channels, sampleRate, channels);
        for (int offset = 0; offset < pcm.Length; offset += 5120 * channels)
            writer.WriteFrame(pcm.AsSpan(offset, Math.Min(5120 * channels, pcm.Length - offset)));
        writer.Complete(); return stream.ToArray();
    }
    private static byte[] OldWav(float[] stereo, int sampleRate = 48000)
    {
        // Independent frozen layout of the previous BinaryWriter/span export.
        using var stream = new MemoryStream(); using var writer = new BinaryWriter(stream, Encoding.ASCII, leaveOpen: true);
        uint dataSize = checked((uint)stereo.Length * 2);
        writer.Write("RIFF"u8); writer.Write(36u + dataSize); writer.Write("WAVEfmt "u8);
        writer.Write(16u); writer.Write((ushort)1); writer.Write((ushort)2); writer.Write(sampleRate);
        writer.Write(sampleRate * 4); writer.Write((ushort)4); writer.Write((ushort)16); writer.Write("data"u8); writer.Write(dataSize);
        foreach (float value in stereo) writer.Write(OfflineExporter.ToPcm16(value));
        writer.Flush(); return stream.ToArray();
    }
    private static Task Commit(string path, FakeStorageFile file, CancellationToken token, Action finalizing)
        => typeof(MainView).GetMethod("CommitExportAsync", BindingFlags.Static | BindingFlags.NonPublic)!
            .CreateDelegate<Func<string, Func<Task<Stream>>, CancellationToken, Action, Task>>()(path, file.OpenWriteAsync, token, finalizing);
    private sealed class FakeStorageFile : IDisposable
    {
        public readonly ProviderStream Output = new();
        public Action? BeforeOpen;
        public int Opens;
        public Task<Stream> OpenWriteAsync()
        {
            Opens++; BeforeOpen?.Invoke(); Output.SetLength(0);
            return Task.FromResult<Stream>(Output);
        }
        public void Dispose() => Output.Dispose();
    }
    private sealed class ProviderStream : MemoryStream
    {
        public Action<CancellationToken>? BeforeWrite, BeforeFlush;
        public bool FailWrite, FailClose, Closed;
        public ProviderStream() { Write("keep"u8); Position = 0; }
        public override ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default)
        {
            BeforeWrite?.Invoke(cancellationToken);
            if (FailWrite) { Write(buffer.Span[..Math.Min(7, buffer.Length)]); throw new IOException("provider write failed"); }
            return base.WriteAsync(buffer, cancellationToken);
        }
        public override Task FlushAsync(CancellationToken cancellationToken)
        { BeforeFlush?.Invoke(cancellationToken); return base.FlushAsync(cancellationToken); }
        public override ValueTask DisposeAsync()
        { Closed = true; base.Dispose(); if (FailClose) throw new IOException("provider close failed"); return ValueTask.CompletedTask; }
    }
    private sealed class PumpContext : SynchronizationContext, IDisposable
    {
        private readonly ConcurrentQueue<(SendOrPostCallback Callback, object? State)> work = new();
        private readonly AutoResetEvent ready = new(false);
        public override void Post(SendOrPostCallback d, object? state) { work.Enqueue((d, state)); ready.Set(); }
        public void RunOne()
        {
            (SendOrPostCallback Callback, object? State) next;
            // A queued callback can be consumed before its AutoResetEvent signal; skip stale signals.
            while (!work.TryDequeue(out next))
                Assert.True(ready.WaitOne(TimeSpan.FromSeconds(10)), "The cooperative exporter did not post a continuation.");
            next.Callback(next.State);
        }
        public void Dispose() => ready.Dispose();
    }
}
