<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault></PropertyGroup><ItemGroup><PackageReference Include="Avalonia"/><PackageReference Include="IconPacks.Avalonia.Material"/><PackageReference Include="Avalonia.Themes.Fluent"/><PackageReference Include="Avalonia.Fonts.Inter"/><ProjectReference Include="../MusicMachine.Core/MusicMachine.Core.csproj"/><ProjectReference Include="../MusicMachine.Audio/MusicMachine.Audio.csproj"/></ItemGroup><ItemGroup><AvaloniaResource Include="../../assets/icon/musicmachine.ico" Link="Assets/musicmachine.ico"/></ItemGroup><ItemGroup><AvaloniaResource Include="Assets/Fonts/**"/></ItemGroup></Project>
